"""add is_active to job_contexts

Revision ID: 057c4744b02f
Revises: e5c6bfff9f95
Create Date: 2026-07-28 00:16:34.346782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '057c4744b02f'
down_revision: Union[str, None] = 'e5c6bfff9f95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_contexts', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('TRUE')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_contexts', 'is_active')
    # ### end Alembic commands ###
