"""remove unique constraint from content_hash

Revision ID: 3485f2af0279
Revises: f2f3e9871eca
Create Date: 2026-07-28 10:54:01.960242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3485f2af0279'
down_revision: Union[str, None] = 'f2f3e9871eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resumes_content_hash', table_name='resumes')
    op.create_index(op.f('ix_resumes_content_hash'), 'resumes', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_content_hash'), table_name='resumes')
    op.create_index('ix_resumes_content_hash', 'resumes', ['content_hash'], unique=True)
    # ### end Alembic commands ###
