"""add phase 3 ai fields to resumes

Revision ID: caf683bd40de
Revises: 3485f2af0279
Create Date: 2026-07-28 12:49:26.545516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf683bd40de'
down_revision: Union[str, None] = '3485f2af0279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    sa.Enum('STRONG_FIT', 'MAYBE', 'NO', name='aitierdecision').create(op.get_bind(), checkfirst=True)

    aistatus = sa.Enum('PENDING_AI', 'AI_SCORED', 'AI_FAILED', name='aistatus')
    aistatus.create(op.get_bind(), checkfirst=True)

    recruiterdecision = sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='recruiterdecision')
    recruiterdecision.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('ai_status', aistatus, nullable=False, server_default=sa.text("'PENDING_AI'")))
    op.add_column('resumes', sa.Column('ai_overall_score', sa.Float(), nullable=True))
    op.add_column('resumes', sa.Column('ai_tier_decision', sa.Enum('STRONG_FIT', 'MAYBE', 'NO', name='aitierdecision'), nullable=True))
    op.add_column('resumes', sa.Column('ai_vector_scores', sa.JSON(), nullable=True))
    op.add_column('resumes', sa.Column('ai_score_justification', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('ai_strong_points', sa.JSON(), nullable=True))
    op.add_column('resumes', sa.Column('ai_missing_skills', sa.JSON(), nullable=True))
    op.add_column('resumes', sa.Column('ai_red_flags', sa.JSON(), nullable=True))
    op.add_column('resumes', sa.Column('ai_raw_response', sa.JSON(), nullable=True))
    op.add_column('resumes', sa.Column('prompt_version', sa.String(length=50), nullable=True))
    op.add_column('resumes', sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('resumes', sa.Column('recruiter_decision', recruiterdecision, nullable=False, server_default=sa.text("'PENDING'")))


def downgrade() -> None:
    op.drop_column('resumes', 'recruiter_decision')
    op.drop_column('resumes', 'scored_at')
    op.drop_column('resumes', 'prompt_version')
    op.drop_column('resumes', 'ai_raw_response')
    op.drop_column('resumes', 'ai_red_flags')
    op.drop_column('resumes', 'ai_missing_skills')
    op.drop_column('resumes', 'ai_strong_points')
    op.drop_column('resumes', 'ai_score_justification')
    op.drop_column('resumes', 'ai_vector_scores')
    op.drop_column('resumes', 'ai_tier_decision')
    op.drop_column('resumes', 'ai_overall_score')
    op.drop_column('resumes', 'ai_status')

    sa.Enum(name='aitierdecision').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='aistatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='recruiterdecision').drop(op.get_bind(), checkfirst=True)
