"""add job_title to job_contexts

Revision ID: f2f3e9871eca
Revises: 057c4744b02f
Create Date: 2026-07-28 09:44:52.788576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2f3e9871eca'
down_revision: Union[str, None] = '057c4744b02f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_contexts', sa.Column('job_title', sa.String(length=255), nullable=False, server_default=sa.text("'UNKNOWN'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_contexts', 'job_title')
    # ### end Alembic commands ###
